name: log github events
on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, closed]
    branches: ["*"]
jobs:
  log:
    runs-on: ubuntu-latest
    env:
      COMMIT_LOG_API: ${{ secrets.COMMIT_LOG_API }}
      COMMITS: ${{ toJSON(github.event.commits) }}
      REPOSITORY_URL: ${{ github.repositoryUrl }}
      EVENT_TYPE: ${{ github.event_name }}
      PR_CREATED_AT: ${{ github.event.pull_request.created_at}}
      PR_CLOSED_AT: ${{ github.event.pull_request.closed_at}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # this is important so git fetches all history.. the actions/checkout by default fetches all history as one commit which throws off stats
      - uses: actions/setup-python@v3
        with:
          python-version: "^3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytz
          pip install requests
          pip install gitcommitlogger
      - name: Build package from latest code
        run: |
          pipenv run python -m build .
      - name: Turn on 'editable' mode
        run: |
          pipenv install -e .
      - name: Debugging
          # make sure the environment variales are present
          echo $REPOSITORY_URL
          echo $EVENT_TYPE
          echo $PR_CREATED_AT
          echo $PR_CLOSED_AT
          echo $COMMITS
          # git show --shortstat --date=format-local:'%m/%d/%Y %H:%M:%S' # show latest commit log
          git log --stat -n $(echo $COMMITS | jq '. | length' ) # a better way to show just the latest commits
      - name: Log pull request opened
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        run: |
          gitcommitlogger -r $(echo $REPOSITORY_URL) -t pull_request_opened -d $(echo $PR_CREATED_AT) -o commit_stats.csv -u $(echo $COMMIT_LOG_API) -v
      - name: Log pull request closed and merged
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          echo $COMMITS > commits.json
          cat commits.json # debugging
          gitcommitlogger -r $(echo $REPOSITORY_URL) -t pull_request_merged -d $(echo $PR_CLOSED_AT) -i commits.json -o commit_stats.csv -u $(echo $COMMIT_LOG_API) -v
      - name: Log push
        run: |
          echo $COMMITS > commits.json
          cat commits.json # debugging
          gitcommitlogger -r $(echo $REPOSITORY_URL) -t $(echo $EVENT_TYPE) -i commits.json -o commit_stats.csv -u $(echo $COMMIT_LOG_API) -v
