name: log commits
on:
  push:
    branches: [main]
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Logging
        run: |
          echo "User: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Commits: ${{ toJSON(github.event.commits) }}"
          echo "Github context: ${{ toJSON(github) }}"
          echo "Job context: ${{ toJSON(job) }}"
