name: log commits
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Logging
        run: |
          echo "User: ${{ github.actor }}"
          echo "Github context: ${{ toJSON(github) }}"
          echo "Job context: ${{ toJSON(job) }}"
